# Generated by Django 5.0.3 on 2024-04-28 10:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_customer_id_alter_food_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='menu_id',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menu')),
                ('translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.translation')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.category'),
        ),
    ]
