# Generated by Django 5.0.3 on 2024-04-28 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_booking_total_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySub',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.category')),
                ('translation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.translation')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='category_sub_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.categorysub'),
        ),
    ]
