# Generated by Django 5.0.3 on 2024-04-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_categorysub_food_category_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_code',
            field=models.CharField(default='', max_length=55),
        ),
    ]
