# Generated by Django 5.0.3 on 2024-04-28 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_category_filter_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='bookingdetail',
            old_name='booking_id',
            new_name='booking',
        ),
        migrations.RenameField(
            model_name='bookingdetail',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='bookingdetail',
            old_name='food_sub_id',
            new_name='food_sub',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='translation_id',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='categorysub',
            old_name='translation_id',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='category_sub_id',
            new_name='category_sub',
        ),
        migrations.RenameField(
            model_name='food',
            old_name='translation_id',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='foodsub',
            old_name='food_id',
            new_name='food',
        ),
        migrations.RenameField(
            model_name='foodsub',
            old_name='translation_id',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='mytable',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
    ]
