# Generated by Django 5.0.3 on 2024-04-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_rename_customer_id_booking_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=90),
        ),
    ]
