# Generated by Django 5.0.3 on 2024-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytable',
            name='table_number',
            field=models.CharField(max_length=10),
        ),
    ]
