# Generated by Django 5.0.3 on 2024-04-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_booking_booking_time_alter_food_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='special_requests',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
