# Generated by Django 5.0.3 on 2024-05-01 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_user_fullname_alter_food_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='translation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.translation'),
        ),
    ]
